// src/data/productsData.js
import image1 from "../image/products/image 1.png";
import image3 from "../image/products/image 3.png";
import image4 from "../image/products/image 4.png";
import image5 from "../image/products/Image 5.png";
import image6 from "../image/products/image 6.png";
import image7 from "../image/products/Images.png";
import image8 from "../image/products/image 8.png";

const products = [
  {
    id: 1,
    name: "Syltherine",
    title: "Stylish cafe chair",
    pricesale: "2.500.000",
    price: "3.500.000",
    sale: "-30%",
    imgSrc: image1,
  },
  {
    id: 2,
    name: "Leviosa",
    title: "Stylish cafe chair",
    pricesale: "2.500.000",
    price: "",
    sale: "",
    imgSrc: image8,
  },
  {
    id: 3,
    name: "Lolito",
    title: "Luxury big sofa",
    pricesale: "7.000.000",
    price: "14.000.000",
    sale: "-50%",
    imgSrc: image3,
  },
  {
    id: 4,
    name: "Respira",
    title: "Outdoor bar table and stool",
    pricesale: "500.000 ",
    price: "3.500.000",
    sale: "New",
    imgSrc: image4,
  },
  {
    id: 5,
    name: "Grifo",
    title: "Night lamp",
    pricesale: "1.500.000",
    price: "3.500.000",
    sale: "",
    imgSrc: image5,
  },
  {
    id: 6,
    name: "Muggo",
    title: "Small mug",
    pricesale: "150.000",
    price: "3.500.000",
    sale: "New",
    imgSrc: image6,
  },
  {
    id: 7,
    name: "Pingky",
    title: "Cute bed set",
    pricesale: "7.000.000",
    price: "14.000.000",
    sale: "-50%",
    imgSrc: image7,
  },
  {
    id: 8,
    name: "Potty",
    title: "Minimalist flower pot",
    pricesale: "500.000",
    price: "",
    sale: "New",
    imgSrc: image8,
  },
  {
    id: 9,
    name: "Syltherine",
    title: "Stylish cafe chair",
    pricesale: "2.500.000",
    price: "3.500.000",
    sale: "-30%",
    imgSrc: image1,
  },
  {
    id: 10,
    name: "Leviosa",
    title: "Stylish cafe chair",
    pricesale: "2.500.000",
    price: "",
    sale: "",
    imgSrc: image8,
  },
  {
    id: 11,
    name: "Lolito",
    title: "Luxury big sofa",
    pricesale: "7.000.000",
    price: "14.000.000",
    sale: "-50%",
    imgSrc: image3,
  },
  {
    id: 12,
    name: "Respira",
    title: "Outdoor bar table and stool",
    pricesale: "500.000 ",
    price: "3.500.000",
    sale: "New",
    imgSrc: image4,
  },
  {
    id: 13,
    name: "Grifo",
    title: "Night lamp",
    pricesale: "1.500.000",
    price: "3.500.000",
    sale: "",
    imgSrc: image5,
  },
  {
    id: 14,
    name: "Muggo",
    title: "Small mug",
    pricesale: "150.000",
    price: "3.500.000",
    sale: "New",
    imgSrc: image6,
  },
  {
    id: 15,
    name: "Pingky",
    title: "Cute bed set",
    pricesale: "7.000.000",
    price: "14.000.000",
    sale: "-50%",
    imgSrc: image7,
  },
  {
    id: 16,
    name: "Potty",
    title: "Minimalist flower pot",
    pricesale: "500.000",
    price: "",
    sale: "New",
    imgSrc: image8,
  },
];

export default products;
